### ISSUE TITLE
[6.3.9] 클래스메서드와 인스턴스메서드

### ISSUE THREAD

**Issue by HyunJungLee2** [gyoungeunbae/standardOfJava#3]
3. 클래스메서드는 인스턴스변수를 사용할 수 없다.
- 인스턴스변수는 인스턴스가 반드시 존재해야만 사용할 수 있다와
클래스메서드에서 인스턴스 변수를 왜 사용할 수 없는지에 대한 부분이 자세하게 궁금합니다..!

**Comment by gyoungeunbae** [comment]
#2 참고 부탁드립니다.
